Src/libCZI/libCZI_Utilities.cpp, Src/libCZI/libCZI_Utilities.h, Src/libCZI_UnitTests/test_LUT.cpp
* Add new function `Create16BitLookUpTableFromGamma` that works similarly to the previously existing `Create8BitLookUpTableFromGamma`.
* Rename `InternalCreate8BitLookUpTableFromGamma` -> `InternalCreateLookUpTableFromGamma`, and generalize the already-templated function so that it is easy to produce LUTs having different types (and then just use the updated function).
* Fix a trivial copy-paste error.
Not really tested just yet. Can look into adding some test automation, if this addition can otherwise be considered? Am new to libCZI, and haven't so far even looked into how the current test suite has been set up.
- The link appears to be dead.
=> Add function to generate 16-bit LUTs from gamma

Src/libCZI/CziAttachment.cpp, Src/libCZI/CziAttachmentsDirectory.cpp, Src/libCZI/CziAttachmentsDirectory.h, Src/libCZI/CziMetadataBuilder.cpp, Src/libCZI/CziMetadataBuilder.h, Src/libCZI/CziParse.cpp, Src/libCZI/CziParse.h, Src/libCZI/CziReaderWriter.cpp, Src/libCZI/CziSubBlockDirectory.cpp, Src/libCZI/CziSubBlockDirectory.h, Src/libCZI/libCZI_Metadata.h, Src/libCZI/stdAllocator.cpp, Src/libCZI/utilities.cpp, Src/libCZI/utilities.h, Src/libCZI_UnitTests/test_DisplaySettings.cpp, Src/libCZI_UnitTests/test_metadatabuilder.cpp
Summary of the change(s) and which issue(s) is/are fixed  
Relevant motivation and context  
Dependencies required for this change  
This is adding support for Writing display settings when creating a CZI
Fixes # (issue)
build runs locally (Linux and Windows)
Tests run successfully
=> Add ability to write DisplaySettings metadata on czi creation

.github/codecov.yml
Remove the [carryforward](https://docs.codecov.com/docs/carryforward-flags) flag from the [codecov](https://docs.codecov.com/docs) scan.
Fixes #33 
Results will be visible/available once pushed to _main_.
=> Remove carryforward flag from codecov

Src/libCZI/CziDisplaySettings.cpp, Src/libCZI/CziParse.cpp, Src/libCZI/CziReaderWriter.cpp, Src/libCZI/CziSubBlockDirectory.cpp, Src/libCZI/CziWriter.cpp, Src/libCZI/Doc/mainpage.markdown, Src/libCZI/libCZI_Utilities.cpp, Src/libCZI/libCZI_Utilities.h, Src/libCZI/splines.cpp, Src/libCZI/splines.h
Some cosmetic and fixing typos. Also, an unused (and non-exported) function was removed.
Fixes some clang-tidy findings.
built locally and ran tests
=> minor cosmetic

CMakeLists.txt, Src/libCZI/CMakeLists.txt, Src/libCZI/libCZI_Site.h, Src/libCZI/pugiconfig.hpp, Src/libCZI/pugixml.cpp, Src/libCZI/pugixml.hpp
* update zstd to version 1.5.4 - which is is a recommended upgrade and seems to have substantial improvements (c.f. [here](https://github.com/facebook/zstd/releases/tag/v1.5.4)).
* ...while at it, I also updated pugixml
* bump libCZI-version
Fixes # (issue)
ran unit-tests on various machines
=> update zstd-version to 1.5.4

CMakeLists.txt, Src/libCZI/CMakeLists.txt, Src/libCZI/SingleChannelScalingTileAccessor.cpp, Src/libCZI/libCZI_Compositor.h, Src/libCZI_UnitTests/CMakeLists.txt, Src/libCZI_UnitTests/test_Accessors.cpp, Src/libCZI_UnitTests/test_readerwriter.cpp, Src/libCZI_UnitTests/utils.cpp, Src/libCZI_UnitTests/utils.h
This is adding unit-tests coverage in the area changed with #48 .
Fixes #49 .
CI/CD on fork
=> add unittest exercising "sortByM"-flag

CMakeLists.txt, Src/libCZI/SingleChannelScalingTileAccessor.cpp, Src/libCZI_UnitTests/test_Accessors.cpp
When using the scaling-accessor, in some cases not pixel-accurate compositions have been found.
This PR avoids using the scaling-blit-operation if zoom is exactly 1, and therefore is giving pixel-accurate results in this case.
A unit-test which exercises on of the problematic cases is added.
running unit-tests locally, testing with CZIcmd
=> fix for "not-pixel-exact result with scaling-accessor if zoom is exactly 1"

CMakeLists.txt, Src/libCZI/CziMetadata.cpp, Src/libCZI/CziMetadata.h, Src/libCZI/CziMetadataBuilder.cpp, Src/libCZI/CziMetadataBuilder.h, Src/libCZI/XmlNodeWrapper.h, Src/libCZI/libCZI_Metadata.h, Src/libCZI_UnitTests/test_DisplaySettings.cpp, Src/libCZI_UnitTests/test_metadatabuilder.cpp, Src/libCZI_UnitTests/test_metadatareading.cpp
When serializing display-settings to CZI-XML, it was found that we better write the element "ColorMode", which explicitly states whether "tinting-mode" is to be used or not.
While at it, I did also some cosmetic and refactoring, and added a feature for the IXmlNodeRead::GetChildNodeReadonly-function: ability to select a specific node by index.
locally
=> Write colormode to displaysettingsxml

.github/workflows/cla.yml
Simplify CLA Check
It turned out that skipped checks are treated as passing. 
Depending on your use case, this can also be seen as undesired behaviour - e.g. in https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt. However, in our scenario, it is as intended and therefore perfectly enough.
This change is complemented by removing the succeed-for-cla status check from the branch protection rule.
PR Experience
=> Remove succeed-for-cla

CMakeLists.txt, Src/libCZI/StreamsLib/curlhttpinputstream.cpp
fix a crash when libcurl was built w/o SSL-support.
locally
=> fix for crash when libcurl is built w/o SSL-support

CMakeLists.txt, Src/CZICmd/cmdlineoptions.cpp, Src/libCZI/StreamsLib/curlhttpinputstream.cpp, Src/libCZI/libCZI_StreamsLib.h
Add two useful options to the property-bag for configuring the "curl_http_inputstream".
locally
=> add option "kCurlHttp_FollowLocation"

CMakeLists.txt, Src/CZICmd/CMakeLists.txt, Src/CZICmd/cmdlineoptions.cpp, Src/CZICmd/cmdlineoptions.h, Src/CZICmd/execute.cpp, Src/CZICmd/executeBase.cpp, Src/CZICmd/executeBase.h, Src/CZICmd/executePlaneScan.cpp, Src/CZICmd/executePlaneScan.h, Src/libCZI/CMakeLists.txt, Src/libCZI/Doc/CZICmd_usage.markdown, Src/libCZI/Doc/version-history.markdown, Src/libCZI/SingleChannelAccessorBase.cpp, Src/libCZI/SingleChannelAccessorBase.h, Src/libCZI/SingleChannelPyramidLevelTileAccessor.cpp, Src/libCZI/SingleChannelScalingTileAccessor.cpp, Src/libCZI/SingleChannelScalingTileAccessor.h, Src/libCZI/SingleChannelTileAccessor.cpp, Src/libCZI/libCZI.h, Src/libCZI/libCZI_Compositor.h, Src/libCZI/subblock_cache.cpp, Src/libCZI/subblock_cache.h, Src/libCZI_UnitTests/CMakeLists.txt, Src/libCZI_UnitTests/test_Accessors.cpp, Src/libCZI_UnitTests/test_SubBlockCache.cpp, Src/libCZI_UnitTests/test_reader.cpp
* adding the option to use a cache with the accessors
* an implementation of a simple cache
* adding an example of its usage to CZIcmd
* unrelated: updated CLI11 to latest version (c.f. [here](https://github.com/CLIUtils/CLI11/releases)), no changes in functionality expected for our usage
* added an option to enable/disable the"non-visible-tile-optimization" from #78 to CZICmd. 
The PR is addressing #77.
With the CZI-document mentioned in #73 I get the following runtimes for
| description | run-time | command line |
| ----  | ----  | ----- |
| with 50MB cache and w/o visibility-check-optimization | 3m 16s | `.\CZIcmd.exe "-c" "PlaneScan" "-p" "C0" "-s" "sample_from_73.czi" "-r" "rel(0,0,44296,36989)" "-o" "I:\scanplane\test" "-z" "1" "--cachesize" "50Mi" -b 0 --tilesize-for-plane-scan …
=> adding ability to use a cache with accessors

CMakeLists.txt, Src/CMakeLists.txt, Src/libCZI/Doc/version-history.markdown
We used `find_package(CURL CONFIG QUIET)` to pull in an externally provided libcurl-library, which means that CMake is only looking for package configuration files (CURLConfig.cmake or curl-config.cmake file). However, those files are not provided e.g. by Debian's 'libcurl4-openssl-dev'-package. So, we fall back to CMake's standard search procedure if `find_package(CURL CONFIG QUIET)`  fails and try again with `find_package(CURL QUIET)`.
This allows us to use the apt-package without further ado in building libCZI, saving quite some time compared to otherwise having to build libcurl ourselves (with vcpkg or as part of libCZI-build).
I chose to bump the version number here, in order to be able to mention this change in the changelog.
In a codespace …
=> small adjustment to how a system-provided libCURL is searched for

.github/workflows/cmake.yml
Replace Codecov token with secret configured on repo level
Old secret regenerated  
Relevant motivation: security  
Dependencies required for this change: None except outlined above
PR
=> Replace Codecov token with secret

.github/workflows/cmake.yml, .github/workflows/mega-linter.yml, CMakeLists.txt, Src/CMakeLists.txt, Src/CZICmd/CMakeLists.txt, Src/Doxyfile, Src/libCZI/CMakeLists.txt, Src/libCZI/Doc/building_libCZI.markdown, Src/libCZI/Doc/stream_objects.markdown, Src/libCZI/Doc/version-history.markdown, Src/libCZI/StreamsLib/azureblobinputstream.cpp, Src/libCZI/StreamsLib/azureblobinputstream.h, Src/libCZI/StreamsLib/streamsFactory.cpp, Src/libCZI/libCZI_StreamsLib.h, Src/libCZI/utilities.cpp, Src/libCZI_UnitTests/CMakeLists.txt, Src/libCZI_UnitTests/test_azureblobstream.cpp, cmake/dummy/azure_c_shared_utilityConfig.cmake, cmake/dummy/azure_macro_utils_cConfig.cmake, cmake/dummy/opentelemetry-cppConfig.cmake, cmake/dummy/umock_cConfig.cmake, cmake/dummy/wilConfig.cmake
* adding an input-stream-object based on Azure-SDK for reading data from Azure-Blob-store
* adding unittests for new functionality
* the required C++ version had to be raised to C++14, because that's required by the Azure-SDK-headers
locally, with CZIcmd, unittests and by beta-users
=> add Azure-SDK-based stream-object

CMakeLists.txt, Src/libCZI/Doc/version-history.markdown, cmake/ExternalEIGEN3.cmake
Building with clang (tested with version 18.1.0rc) yields an error in the configuration step of the external eigen package.
Explicitly disabling this (it is implicitly skipped when building with msvc) solves this problem and the project builds fine with clang on windows.
Fixes # (issue)
Locally tested using clang from the official [LLVM releases](https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.0). Configuring the project with `export CC=$(which clang) && export CXX=$(which clang++) && cmake -B build -S . -G Ninja` (ensuring the `which clang` and `which clang++` calls point to the correct locations of the compilers).
I've tested both, Release and Debug configurations + used this fork in an external project that includes libczi via `FetchContent_Declare`.  …
=> Explicitly disable the configure command for eigen (ext)

CMakeLists.txt, Src/CZICmd/CMakeLists.txt, Src/libCZI/Doc/version-history.markdown
The CMake-build failed when using a private RapidJSON-library (i.e. when LIBCZI_BUILD_PREFER_EXTERNALPACKAGE_RAPIDJSON would be false) when attempting to clone the repository because when specifying "GIT_SHALLOW TRUE" it is not possible to use a git-hash as tag. C.f. [here](https://cmake.org/cmake/help/latest/module/ExternalProject.html).
This removes the GIT_SHALLOW specifier, and while at it, switches to the latest version.
locally
=> fix build when using a private RapidJSON library

.github/workflows/cmake.yml, CMakeLists.txt, Src/libCZI/Doc/stream_objects.markdown, Src/libCZI/Doc/version-history.markdown, Src/libCZI/StreamsLib/azureblobinputstream.cpp, Src/libCZI/StreamsLib/azureblobinputstream.h
* fixed documentation to state the same string as expected in code
* add error handling to AzureBlobInputStream::Read method
Fixes #118 
locally
=> rename accountURL for consistency

CMakeLists.txt, Src/libCZI/Doc/version-history.markdown, Src/libCZI/StreamsLib/azureblobinputstream.cpp
fix workload identity in azure reader
locally build.
=> fix workload identity in azure reader

Src/libCZI_UnitTests/utils.cpp
Following up on #126 
- use C++ RNG instead of rand()
- minor cosmetic
locally
=> replace rand() with C++ RNG (in unit-test)

.github/workflows/pages.yml, Src/libCZI/decoder_wic.cpp
* update GH-action to use v4 of upload-artifact action (c.f. [here](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/))
* cosmetic (remove unused code)
Only CI/CD has changed.
=> actions-upload-artifact-v3 obsolescence

CMakeLists.txt, Src/libCZIAPI/inc/external_stream_error_information_struct.h, Src/libCZIAPI/inc/libCZIApi.h, Src/libCZIAPI/src/libCZIApi.cpp, Src/libCZIAPI/src/parameterhelpers.h, docs/source/pages/coordinate_systems.rst, docs/source/pages/version_history.md
* enable "proper error-handling" for "external stream"-functionality in libCZIAPI
* fix some formatting issues in the documentation
locally, and test code is included in the upcoming .NET-API
=> fix error-handling for "external streams" in libCZIAPI

CMakeLists.txt, Src/libCZIAPI/inc/libCZIApi.h, Src/libCZIAPI/src/libCZIApi.cpp, Src/libCZIAPI_UnitTests/test_CZIReader.cpp, Src/libCZIAPI_UnitTests/utilities.cpp, Src/libCZIAPI_UnitTests/utilities.h, docs/source/pages/version_history.md
This pull request introduces a new method, TryGetSubBlockInfoForIndex, to the libCZI API, which allows users to retrieve information about sub-blocks at a specified index. The new function uses the TryGetSubBlockInfo function instead of the ReadSubBlock function to get the subblock information at the specified index.
This PR supersedes #137 
The test named "ConstructExternalInputStreamAndTryGetSubBlockInfoForIndex" was written to the test_CZIReader.cpp file.
This unit test checks the sub-block information at index 0.
=> add SubBlockInfoForIndex extension for libCZIAPI 

docs/source/pages/building.rst
I'm currently developing a Java library that wraps `libCZI` using the Foreign Function & Memory (FFM) API. While configuring my build, I noticed that the build option documentation seems to be slightly out of sync with the options defined in `CMakeLists.txt`.
It appears some option names in the documentation are missing an underscore (e.g., `LIBCZI_BUILDDYNLIB` should be `LIBCZI_BUILD_DYNLIB`), and at least one new option is not listed (`LIBCZI_BUILD_PREFER_EXTERNALPACKAGE_RAPIDJSON`). 
Fixes #140 
- Updates documentation
- Makes no other changes
=> Update build options

Src/JxrDecode/jxrlib/image/decode/segdec.c, Src/JxrDecode/jxrlib/image/decode/strdec.c, Src/JxrDecode/jxrlib/image/encode/strenc.c
In previous PR #146  a few function were forgotten.
-> https://github.com/ptahmose/libczi-vcpkg-test/actions/runs/16721353933/job/47326310641
=> Add JXRLIB_API macro to some forgotten jxrlib-functions
